name: Continuous Integration
on: [push]                      # Will make the workflow run every time you push to any branch

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code

    - name: Hello world
      uses: actions/hello-world-javascript-action@v1.1 # Name of the action. This uses https://github.com/actions/hello-world-javascript-action
      with:                                            # This section is needed if you need to pass arguments to the action
        who-to-greet: 'Mona the Octocat'

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x

    - name: Build C# code
      run: dotnet build --configuration Release

    - name: Test C# code
      run: dotnet test

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

  

    - name: Install dependencies
      working-directory: ./DotnetTemplate.Web
      run: npm ci

    - name: Build TypeScript code
      working-directory: ./DotnetTemplate.Web
      run: npm run build

    - name: Run linter
      working-directory: ./DotnetTemplate.Web
      run: npm run lint

    - name: Test TypeScript code
      working-directory: ./DotnetTemplate.Web
      run: npm test

     




